### ISSUE TITLE
Merge branch bevy-0.6 to main

### ISSUE THREAD

**Issue by schnippl0r** [lightsoutgames/bevy_input_actionmap#13]
Please merge branch `bevy-0.6` into `main`.

I wanted to create a PR with the changes needed for the migration to bevy 0.6 but after I was finished committing to my own fork, I saw that the branch `bevy-0.6` existed and that the work was already done.

You can find my changes at https://github.com/schnippl0r/bevy_input_actionmap/commit/4339780c4725cc7c0e82efcafcc61b8d16c7aa0e

Well, as my code changes are the same as the changes in branch `bevy-0.6`, I guess you can consider it a code review. :)

**Comment by ndarilek** [comment]
Definitely, give me a day or so to finish porting my game first. Down from 319 errors to 73, so should be quick.

Closing since that's the plan. Sorry for the gap--hit some porting issues that slowed me down.
